name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous-integration:
    runs-on: windows-2022

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.x"

      - name: Install
        run: |
          npm ci
          npm ls

      - name: "Continuous Integration: lint"
        run: |
          npm run lint --if-present

      - name: "Continuous Integration: build"
        run: |
          npm run build --if-present

      - name: "Continuous Integration: test"
        run: |
          npm run test --if-present
